name: Welcome First-Time Contributor v3

env:
  ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
  ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
  
on:
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Debug author association
        run: |
             echo "Author Association: ${{ github.event.pull_request.author_association }}"
             echo "User: ${{ github.event.pull_request.user.login }}"
             
      - name: Post welcome message if first-time contributor
        if: |
          github.event.pull_request.author_association == 'FIRST_TIMER' || 
          github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' || 
          github.event.pull_request.author_association == 'NONE' &&
          github.event.pull_request.author_association != 'CONTRIBUTOR'
          
        uses: actions/github-script@v7
        with:
          script: |
            const login = context.payload.pull_request.user.login;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = 'master'; // or 'master' or your default branch name

            const imageUrl = `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/images/1stpr.png`;

            const message = `
            🎉 Thank you @${context.payload.pull_request.user.login} for your **first contribution**! 🎉  

            ![Sticker](${imageUrl})

            We’re thrilled to have you join the project — welcome aboard! 🚀
            `;

            // Post a comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
          

